title = "Montréal-Senneterre"
heading = "Montréal-Senneterre"
aria_label = "Montréal Senneterre"
reference_date = "20240601"
bottom_text = "<b>Stops between two stations:</b> On this train, you can request a stop at a specific mile marker if requested 48 hours in advance. Contact <a href=\"https://www.viarail.ca/en/explore-our-destinations/stations/stops-between-two-explore-our-destinations/stations\">VIA Rail</a> for details.<br><br><b>The Jonquiere and Senneterre trains run combined:</b> between Montreal and Hervey, they are the same train, and cars split or join at Hervey."
key_on_right = true
key_baggage = true
key_f = true
key_tz = true
wheelchair_advance_notice = true
for_rpa = true
