title = "Corridor Southwest Ontario Away From Toronto"
heading = "Southwest Ontario services Away From Toronto"
aria_label = "Southwest Ontario Outbound"
reference_date = "20240606"
bottom_text = "The <b>Maple Leaf</b> is operated jointly by VIA Rail and <img class=\"amtrak_logo\" src=\"logos/Amtrak_logo_2.svg\" alt=\"Amtrak\" title=\"Amtrak\"><a href=\"https://www.amtrak.com/\">Amtrak</a>. See separate timetable for details."
key_r = true
key_d = true
wheelchair_advance_notice = true
for_rpa = true
