title = "Berkshire Flyer Timetable"
heading = "Berkshire Flyer"
aria_label = "Berkshire Flyer"
top_text = "The Berkshire Flyer is a seasonal train service that runs on Fridays & Sundays from late May through early October. The train will run on Mondays for the Memorial Day and Labor Day holidays.  See more information at <b><a href=\"https://www.berkshire-flyer.com/\">www.berkshire-flyer.com</a> and <b><a href=\"https://www.amtrak.com/berkshire-flyer-train\">www.amtrak.com/berkshire-flyer-train</a></b>"
reference_date = "20240623"
key_d = true
key_r = true
for_rpa = true
