title = "Berkshire Flyer Timetable"
heading = "Berkshire Flyer"
aria_label = "Berkshire Flyer"
top_text = "The Berkshire Flyer is a seasonal train service that runs from Memorial Day weekend through Columbus Day weekend 2023.  See more information at <b><a href=\"https://www.berkshire-flyer.com/\">www.berkshire-flyer.com</a></b>"
programmers_warning = "This tests to make sure that NoTripError is thrown correctly, so it deliberately uses a date when the Berkshire Flyer is known to not operate."
reference_date = "20240130"
key_d = true
key_r = true
for_rpa = true
