title = "Ethan Allen Express Timetable"
heading = "Ethan Allen Express & Burlington Buses"
aria_label = "Ethan Allen Express"
reference_date = "20240601"
key_on_right = true
key_bus = true
use_bus_icon_in_cells = true
landscape = true
for_rpa = true
