title = "Amtrak's Northeast Corridor: Weekday Southbound 3"
heading = "Northeast Corridor: Weekday Southbound 3"
reference_date = "20240102"
landscape = true
key_on_right = true
key_baggage = true
key_d = true
key_r = true
for_rpa = true
